<a href="https://colab.research.google.com/github/KovryakRuslan312005/CH_M_Kovryak/blob/main/%D0%9B%D0%91%E2%84%964%20%D0%9A%D0%BE%D0%B2%D1%80%D1%8F%D0%BA%20%D0%A0%D1%83%D1%81%D0%BB%D0%B0%D0%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Завдання 1(приклад 2)
import numpy as np

# Define matrices A and B
A = np.array([[2, 3, 1],
              [-1, 1, 0],
              [1, 2, -1]])

B = np.array([[1, 2, 1],
              [0, 1, 2],
              [3, 1, 1]])

# Calculate C = AB - BA
C = np.dot(A, B) - np.dot(B, A)

print("Matrix C:")
print(C)

Matrix C:
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [ ]:
#Завдання №2 (приклад 3)
import numpy as np

# Define matrix A as a NumPy array
matrix_A = np.array([[5, 0, 0, 0],
                     [0, -2, 0, 0],
                     [0, 0, 3, 0],
                     [0, 0, 0, 2]])

# Calculate F = A^2
matrix_F = np.dot(matrix_A, matrix_A)

print(matrix_F)

[[25  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0  4]]


In [ ]:
#Завдання 3(приклад 2)
matrix_A = np.array([[5, 8, -4],
                      [6, 9, -5],
                      [4, 7, -3]])

matrix_B = np.array([[3, 2, 5],
                      [4, -1, 3],
                      [9, 6, 7]])

# Calculate the product of A and B
product = np.dot(matrix_A, matrix_B)

print("Product of matrices A and B:")
print(product)

Product of matrices A and B:
[[ 11 -22  21]
 [  9 -27  22]
 [ 13 -17  20]]


In [ ]:
#Завдання 4(приклад 3)
import numpy as np

# Define matrix A as a NumPy array
matrix_A = np.array([[2, 4, 5],
                     [1, 1, 2],
                     [2, 4, 3]])

# Calculate the determinant of matrix A
matrix_A_det = np.linalg.det(matrix_A)

print("Determinant of matrix A:")
print(matrix_A_det)

Determinant of matrix A:
4.0


In [ ]:
#Завдання 5(приклад 2)
import numpy as np

# Оголошення матриці як NumPy array
matrix = np.array([[2, 3, 4, 1],
                   [1, 2, 3, 4],
                   [3, 4, 1, 2],
                   [4, 1, 2, 3]])

# Обчислення визначника матриці
determinant = np.linalg.det(matrix)

print("Determinant of the matrix:")
print(determinant)


Determinant of the matrix:
-160.00000000000009


In [ ]:
#Завдання 6(приклад 3)
import numpy as np

# Оголошення матриці як NumPy array
matrix_A = np.array([[1, 2, 2],
                     [2, 1, -2],
                     [2, -2, 1]])

# Обчислення оберненої матриці
matrix_A_inv = np.linalg.inv(matrix_A)

print("Inverse of matrix A:")
print(matrix_A_inv)

Inverse of matrix A:
[[ 0.11111111  0.22222222  0.22222222]
 [ 0.22222222  0.11111111 -0.22222222]
 [ 0.22222222 -0.22222222  0.11111111]]


In [ ]:
#Завдання 7(приклад 2)
import numpy as np

# Оголошення матриці як NumPy array
matrix = np.array([[1, -1, 3, 4],
                   [0, -1, 2, 1],
                   [1, 1, -1, 2],
                   [2, 3, -5, 3]])

# Обчислення рангу матриці
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:")
print(rank)

Rank of the matrix:
3


In [ ]:
#Завдання №8 (варіант 9)
import numpy as np

# Оголошення матриці системи лінійних рівнянь A та вектора результатів B
A = np.array([[1, -2, 3],
              [4, 2, -3],
              [3, -3, 5]])

B = np.array([-5, 0, -9])

# Метод Крамера
det_A = np.linalg.det(A)
x = np.linalg.det(np.column_stack((B, A[:, 1], A[:, 2]))) / det_A
y = np.linalg.det(np.column_stack((A[:, 0], B, A[:, 2]))) / det_A
z = np.linalg.det(np.column_stack((A[:, 0], A[:, 1], B))) / det_A

print("Корені за методом Крамера:", x, y, z)

# Матричний метод (обчислення оберненої матриці)
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Корені за матричним методом:", X)

# Метод Гауса
X = np.linalg.solve(A, B)

print("Корені за методом Гауса:", X)

Корені за методом Крамера: -1.0000000000000004 1.9999999999999996 0.0
Корені за матричним методом: [-1.0000000e+00  2.0000000e+00 -8.8817842e-16]
Корені за методом Гауса: [-1.  2. -0.]


In [ ]:
#Завдання №9 (приклад 5)
import numpy as np

def random_matrix_sum(N, M):
    # Створення прямокутної матриці з випадковими елементами
    A = np.random.randint(1, 10, size=(N, M))

    # Знайдемо суму всіх елементів матриці
    total_sum = np.sum(A)

    # Створимо пустий список для зберігання сум кожного рядка
    row_sums = []

    # Обчислимо суму елементів кожного рядка
    for row in A:
        row_sum = np.sum(row)
        row_sums.append(row_sum)

    # Перетворимо список в NumPy array
    row_sums = np.array(row_sums)

    # Визначимо, яку долю в цій сумі складає сума елементів кожного рядка
    row_sum_fraction = row_sums / total_sum

    return A, total_sum, row_sum_fraction

# Виклик функції з вказаним розміром матриці
N = 5
M = 3
matrix, total_sum, row_sum_fraction = random_matrix_sum(N, M)

# Виведення результатів
print("Прямокутна матриця A:")
print(matrix)
print("\nСума всіх елементів матриці:", total_sum)
print("\nДоля суми елементів кожного рядка у сумі всіх елементів матриці:")
print(row_sum_fraction)

Прямокутна матриця A:
[[4 1 5]
 [7 7 7]
 [9 1 9]
 [5 2 2]
 [5 3 5]]

Сума всіх елементів матриці: 72

Доля суми елементів кожного рядка у сумі всіх елементів матриці:
[0.13888889 0.29166667 0.26388889 0.125      0.18055556]
